"""Emit the light and dark variants of each hand-authored SVG, and an animated GIF of each.

Why variants exist, given that the master already carries a `prefers-color-scheme` block:
**that block does not work where it matters.** An SVG referenced by an `<img>` tag — which is
how GitHub renders every image in a README — does not inherit the host page's colour scheme,
so the media query resolves against the browser default and a reader in light mode gets the
dark palette. This was measured, not assumed: forcing light mode in a headless browser left
the diagram's cards dark. GitHub's supported answer is a `<picture>` element with two files
and a `media` attribute. So: one master, two emitted variants, nothing hand-maintained twice.

**Why GIF and not PNG.** Devpost accepts JPG, PNG and GIF and does **not** accept SVG, so the
animation that carries the diagram on GitHub cannot reach a judge on the submission page at
all — unless it is a GIF. A still PNG would have thrown the motion away at exactly the surface
that cannot recover it. GIF's 256-colour palette is not a problem here because the diagrams are
flat fills and antialiased text; measured output is well under Devpost's 5 MB image cap at full
1920x1080.

    python scripts/render_diagrams.py              # variants, and GIFs if the tools exist
    python scripts/render_diagrams.py --check      # fail if a variant is stale (CI has neither)
    python scripts/render_diagrams.py --no-gif     # variants only, and fast

**GIFs are not checked.** They need a browser and ffmpeg that this machine happens to have and
CI does not, and two runs are not byte-identical anyway. The SVG variant is the checked
artifact; the GIF is derived from it.

## The two things that were measured rather than assumed

**`--virtual-time-budget` does not advance SMIL.** Rendering the same file at 200ms, 1600ms,
3200ms and 4400ms produced four byte-identical PNGs. An earlier version of this script passed
that flag with a comment claiming it advanced the animation past its opening keyframes; it
never did, and every "frame" was time zero. Seeking has to be explicit, so each frame is an
HTML wrapper that calls `svg.pauseAnimations()` and then `svg.setCurrentTime(t)`.

**The filmstrip trick does not survive contact with a gradient.** Stacking fifteen copies of
the SVG in one tall page, each seeked to its own time, and slicing the screenshot afterwards is
seven times faster — and wrong. Two cells rendered at the *same* animation time differed in 7%
of their pixels, by up to 34 of 255 per channel, across text and empty background alike:
Chromium's rasterisation is not position-independent down a 16,200px page. The damage showed up
as size rather than as a visibly broken frame — every frame differed from its neighbour
everywhere, so inter-frame compression had nothing to elide and the banner GIF went from
0.5 MB to 6.5 MB. One launch per frame is byte-identical across repeat runs, which was
measured too, so that is what this does; the cost is bought back with threads rather than
with a trick.

Every SMIL duration in the masters divides LOOP_SECONDS exactly. That is a constraint on the
artwork, not a coincidence: an animation on a 3.2s cycle sampled over a 6s window is mid-stride
when the GIF loops, and the jump is visible.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Every directory holding hand-authored masters. Both are listed because the 16:9 banner has
# exactly the same theme problem as the diagrams and there is no reason to solve it twice.
SOURCES = (ROOT / "assets" / "architecture", ROOT / "assets" / "brand")

LIGHT_BLOCK = re.compile(r"/\* PALETTE:LIGHT \*/(.*?)/\* /PALETTE:LIGHT \*/", re.DOTALL)
DARK_BLOCK = re.compile(r"/\* PALETTE:DARK \*/(.*?)/\* /PALETTE:DARK \*/", re.DOTALL)

# The master's dark palette lives inside a media query; the emitted dark file must apply it
# unconditionally, so the wrapper is stripped and the declarations promoted.
MEDIA_WRAPPER = re.compile(r"@media \(prefers-color-scheme: dark\) \{(.*)\}", re.DOTALL)

BANNER = "<!-- GENERATED by scripts/render_diagrams.py from {master}. Do not edit. -->"
GENERATED_LINE = re.compile(r"^<!-- GENERATED by .*-->\n", re.MULTILINE)

WIDTH, HEIGHT = 1920, 1080
LOOP_SECONDS = 6
FPS = 12.5
FRAMES = int(LOOP_SECONDS * FPS)

# One headless launch per frame, run concurrently. Six is enough to saturate the disk without
# the launches starving each other; the work happens in Chromium, not in Python.
WORKERS = 6

# Devpost accepts JPG, PNG and GIF, never SVG, and caps a gallery image here.
DEVPOST_IMAGE_CAP_MB = 5

# Headless Chromium renders each frame. Edge ships with Windows and Chrome does not, so both
# are tried; CI has neither, which is why --check never touches the GIFs.
BROWSERS = (
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    "chromium",
    "google-chrome",
)

FRAME_PAGE = """<!doctype html><html><head><style>
html,body{{margin:0;padding:0;overflow:hidden}}
</style></head><body>
{svg}
<script>
var svg = document.querySelector("svg");
svg.pauseAnimations();
svg.setCurrentTime({t});
</script></body></html>"""


def masters() -> list[Path]:
    """Every SVG carrying palette sentinels and not itself an emitted variant."""
    found: list[Path] = []
    for directory in SOURCES:
        for path in sorted(directory.glob("*.svg")):
            if path.stem.endswith(("-light", "-dark")):
                continue
            if LIGHT_BLOCK.search(path.read_text(encoding="utf-8")):
                found.append(path)
    return found


def variant(source: str, master_name: str, *, dark: bool) -> str:
    light_match = LIGHT_BLOCK.search(source)
    dark_match = DARK_BLOCK.search(source)
    if light_match is None or dark_match is None:
        raise SystemExit(f"{master_name}: missing PALETTE:LIGHT / PALETTE:DARK sentinels")

    if dark:
        inner = MEDIA_WRAPPER.search(dark_match.group(1))
        if inner is None:
            raise SystemExit(f"{master_name}: dark palette is not wrapped in a media query")
        palette = inner.group(1)
    else:
        palette = light_match.group(1)

    out = source[: light_match.start()] + palette + source[dark_match.end() :]
    return out.replace("<svg ", BANNER.format(master=master_name) + "\n<svg ", 1)


def tool(candidates: tuple[str, ...]) -> str | None:
    for candidate in candidates:
        if Path(candidate).exists():
            return candidate
        found = shutil.which(candidate)
        if found:
            return found
    return None


def run(argv: list[str], *, timeout: int) -> bool:
    try:
        completed = subprocess.run(  # noqa: S603 - fixed argv, no shell
            argv, capture_output=True, text=True, timeout=timeout, check=False
        )
    except subprocess.TimeoutExpired, OSError:
        return False
    return completed.returncode == 0


def capture_one(body: str, index: int, binary: str, workdir: Path) -> bool:
    """Render a single frame at index/FPS seconds into the animation."""
    page = workdir / f"seek{index:03d}.html"
    page.write_text(FRAME_PAGE.format(svg=body, t=round(index / FPS, 4)), encoding="utf-8")
    target = workdir / f"frame{index:03d}.png"
    ok = run(
        [
            binary,
            "--headless",
            "--disable-gpu",
            "--hide-scrollbars",
            "--force-device-scale-factor=1",
            f"--window-size={WIDTH},{HEIGHT}",
            "--virtual-time-budget=800",
            f"--screenshot={target}",
            page.resolve().as_uri(),
        ],
        timeout=120,
    )
    return ok and target.exists()


def capture_frames(svg: Path, binary: str, workdir: Path) -> int:
    """Render FRAMES stills of one SVG into workdir as frame000.png … Returns how many.

    The SVG is inlined into the wrapper rather than referenced, because `setCurrentTime` needs
    a live SVG document in the page — an `<img src="…svg">` exposes no such handle.

    Threaded because each launch is its own process and spends its time waiting on one; the
    work is not Python's, so the GIL is not the limit here.
    """
    body = GENERATED_LINE.sub("", svg.read_text(encoding="utf-8"))
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        results = pool.map(lambda i: capture_one(body, i, binary, workdir), range(FRAMES))
    return sum(1 for ok in results if ok)


def assemble_gif(workdir: Path, target: Path, ffmpeg: str) -> bool:
    """Frames to GIF via palettegen/paletteuse — the quality path, not ffmpeg's default.

    `stats_mode=diff` builds the palette from what actually changes between frames rather than
    from the whole image, which matters here: most of every frame is static chrome, and a
    whole-image palette spends its 256 slots on background it did not need to.

    **`dither=none` is a size decision, and it is the difference between shipping and not.**
    Dithering perturbs individual pixels across the whole frame, including the parts that never
    move, so every frame differs from the last everywhere and inter-frame compression has
    nothing to elide. On the gradient banner that produced a 5.83 MB GIF — over Devpost's 5 MB
    image cap. Undithered it is 0.48 MB, a twelvefold reduction, and the banding it trades away
    is invisible: the diagrams are flat fills with antialiased text, and the banner's background
    gradient spans four steps of grey. Measured both ways before choosing.
    """
    return run(
        [
            ffmpeg,
            "-y",
            "-v",
            "error",
            "-framerate",
            str(FPS),
            "-i",
            str(workdir / "frame%03d.png"),
            "-vf",
            "split[a][b];[a]palettegen=stats_mode=diff[p];"
            "[b][p]paletteuse=dither=none:diff_mode=rectangle",
            "-loop",
            "0",
            str(target),
        ],
        timeout=300,
    )


def render_gif(svg: Path, binary: str, ffmpeg: str) -> Path | None:
    target = svg.with_suffix(".gif")
    with tempfile.TemporaryDirectory(prefix="bastion-gif-") as raw:
        workdir = Path(raw)
        if capture_frames(svg, binary, workdir) != FRAMES:
            return None
        if not assemble_gif(workdir, target, ffmpeg):
            return None
    return target if target.exists() else None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if a variant is stale")
    parser.add_argument("--no-gif", action="store_true", help="skip the animated GIFs")
    arguments = parser.parse_args()

    found = masters()
    if not found:
        print("no masters with palette sentinels found")
        return 1

    stale: list[str] = []
    written: list[Path] = []

    for master in found:
        source = master.read_text(encoding="utf-8")
        for dark in (False, True):
            target = master.with_name(f"{master.stem}-{'dark' if dark else 'light'}.svg")
            expected = variant(source, master.name, dark=dark)

            if arguments.check:
                current = target.read_text(encoding="utf-8") if target.exists() else ""
                if current != expected:
                    stale.append(target.name)
                continue

            target.write_text(expected, encoding="utf-8")
            written.append(target)

    if arguments.check:
        if stale:
            print("stale variants: " + ", ".join(stale))
            print("run: python scripts/render_diagrams.py")
            return 1
        print(f"Theme variants are current ({len(found)} masters).")
        return 0

    print(f"wrote {len(written)} variant(s) from {len(found)} master(s)")

    if arguments.no_gif:
        return 0

    binary = tool(BROWSERS)
    ffmpeg = tool(("ffmpeg",))
    missing = [
        name for name, found_at in (("a browser", binary), ("ffmpeg", ffmpeg)) if not found_at
    ]
    if missing or binary is None or ffmpeg is None:
        print(f"skipped GIFs — {' and '.join(missing)} not found (the SVGs are the source)")
        return 0

    for target in written:
        gif = render_gif(target, binary, ffmpeg)
        if gif is None:
            print(f"  {target.stem}: GIF FAILED")
            continue
        megabytes = gif.stat().st_size / 1_048_576
        over = "  OVER Devpost's 5 MB cap" if megabytes > DEVPOST_IMAGE_CAP_MB else ""
        print(f"  {gif.name}  {megabytes:.2f} MB{over}")
    print(f"GIFs: {FRAMES} frames, {LOOP_SECONDS}s loop at {FPS}fps, {WIDTH}x{HEIGHT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
